name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: false
          rustflags: ""

      - uses: Swatinem/rust-cache@v2

      - name: Dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake libclang-dev libsdl2-dev

      - name: Build
        run: cargo build --verbose

  test-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: false
          rustflags: ""

      - uses: Swatinem/rust-cache@v2

      - name: Dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake libclang-dev libsdl2-dev

      - name: Test
        run: cargo test --verbose

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: false
          rustflags: ""

      - uses: Swatinem/rust-cache@v2

      - name: Dependencies
        run: brew install sdl3

      - name: Build
        run: LIBRARY_PATH="$(brew --prefix)/lib" cargo build --verbose

  test-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: false
          rustflags: ""

      - uses: Swatinem/rust-cache@v2

      - name: Dependencies
        run: brew install sdl3

      - name: Test
        run: LIBRARY_PATH="$(brew --prefix)/lib" cargo test --verbose

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: false
          rustflags: ""

      - uses: Swatinem/rust-cache@v2

      - name: Dependencies
        run: |
            curl -L "https://github.com/libsdl-org/SDL/releases/download/release-3.4.10/SDL3-devel-3.4.10-VC.zip" --output C:\SDL3-3.4.10.zip
            7z x C:\SDL3-3.4.10.zip -oC:\
            echo "C:/SDL3-3.4.10/lib/x64/" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8

      - name: Build
        env:
          SDL3_DIR: C:/SDL3-3.4.10/cmake/
        run: cargo build --verbose

  test-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: false
          rustflags: ""

      - uses: Swatinem/rust-cache@v2

      - name: Dependencies
        run: |
            curl -L "https://github.com/libsdl-org/SDL/releases/download/release-3.4.10/SDL3-devel-3.4.10-VC.zip" --output C:\SDL3-3.4.10.zip
            7z x C:\SDL3-3.4.10.zip -oC:\
            echo "C:/SDL3-3.4.10/lib/x64/" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8

      - name: Test
        env:
          SDL3_DIR: C:\SDL3-3.4.10\cmake\
        run: cargo test --verbose
